site_name: Credit Risk Assessment
site_url: https://Tobias-GH-Schulz.github.io/credit-risk-assessment-capstone/ 
repo_url: https://www.github.com/tobias-gh-schulz/credit-risk-assessment-capstone
repo_name: tobias-gh-schulz/credit-risk-assessment-capstone

theme:
  name:
    material
  language:
    en
  plugins:
    - search
nav:
  - Introduction: 'index.md'
  - EDA: 'eda.md'
  - Model evaluation: 'model_evaluation.md'
  - Model explainability: 'model_explainability.md'